---
# Extract the installation archive to the remote node
- name: Extract {{ aap_bundled_setup_archive }} on the remote node
  ansible.builtin.unarchive:
    src: "{{ aap_bundled_setup_archive }}.tar.gz"
    dest: "/home/ansible"

# Populate the inventory file
- name: Populate the installers inventory
  ansible.builtin.template:
    src: inventory.j2
    dest: "/home/ansible/{{ aap_bundled_setup_archive }}/inventory"

# Enter the installation path and execute the setup script
- name: Start the installation from the correct path
  ansible.builtin.command: "chdir=/home/ansible/{{ aap_bundled_setup_archive }} ./setup.sh"

...
